train_bert:
    data_dir : "./data"
    bert_model : "bert-base-uncased"
    task_name : "toxic_comments"
    do_train : True
    do_eval : True
    do_lower_case : True
    output_dir : "./model"
    labels : "./data/labels.txt"
    max_seq_length : 64
    train_batch_size : 32
    eval_batch_size : 8
    learning_rate : 5e-5
    num_train_epochs : 3
    warmup_proportion : 0.1
    no_cuda : False
    local_rank : -1
    seed : 42
    gradient_accumulation_steps : 1
    fp16: False
    loss_scale: 0
inference_bert:
    bert_model : 'bert-base-uncased'
    num_labels : 2
    output_model_file : './data/model/pytorch_model.bin'
    label_list : "./data/labels.txt"
    max_seq_length : 64
